FROM python:3.9-slim AS build
WORKDIR /app
COPY Pipfile Pipfile.lock nea-translator.proto ./
RUN pip install pipenv && pipenv install --system --deploy
RUN pipenv install &&\
    pipenv run build
COPY . .
ARG APP_VERSION=local
ENV APP_VERSION=$APP_VERSION
