# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nea-translator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14nea-translator.proto\x12\rneatranslator\"K\n\x12TranslationRequest\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x14\n\x0cnivel_de_nea\x18\x02 \x01(\x05\x12\x0e\n\x06region\x18\x03 \x01(\t\")\n\x13TranslationResponse\x12\x12\n\ntraduccion\x18\x01 \x01(\t2e\n\rNeaTranslator\x12T\n\tTranslate\x12!.neatranslator.TranslationRequest\x1a\".neatranslator.TranslationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nea_translator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSLATIONREQUEST']._serialized_start=39
  _globals['_TRANSLATIONREQUEST']._serialized_end=114
  _globals['_TRANSLATIONRESPONSE']._serialized_start=116
  _globals['_TRANSLATIONRESPONSE']._serialized_end=157
  _globals['_NEATRANSLATOR']._serialized_start=159
  _globals['_NEATRANSLATOR']._serialized_end=260
# @@protoc_insertion_point(module_scope)
